# Numpy

## Лабораторная работа №1

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [68]:
import numpy as np
data_names = np.loadtxt('minutes_n_ingredients.csv', dtype = 'str', delimiter = ',', max_rows = 1) #создание массива названий столбцов датасета
data = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter = ',', skiprows = 1) #создание массива без первой строки - названий столбцов
print(data_names, data[:5,:], sep = '\n') #вывод названий столбцов и массива данных

['id' 'minutes' 'n_ingredients']
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [69]:
mean_data = data[:,1::].mean(0) #вычисление средних значений 1 и 2 столбца
min_data = data[:,1::].min(0) #вычисление минимальных значений 1 и 2 столбца
max_data = data[:,1::].max(0) #вычисление максимальных значений 1 и 2 столбца
median_data = np.median(data[:,1::],0) #вычисление медианных значений 1 и 2 столбца
print('средние значения (минуты, количество ингредиентов)', mean_data,'минимальные значения (минуты, количество ингредиентов)', min_data,'максимальные значения (минуты, количество ингредиентов)', max_data,'медианные значения (минуты, количество ингредиентов)', median_data, sep = '\n') #вывод искомых значений

средние значения (минуты, количество ингредиентов)
[2.16010017e+04 9.05528000e+00]
минимальные значения (минуты, количество ингредиентов)
[0 1]
максимальные значения (минуты, количество ингредиентов)
[2147483647         39]
медианные значения (минуты, количество ингредиентов)
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [70]:
upper_quartile_minutes = np.quantile(data[:,1],0.75) # вычисление верхнего квартиля
data[(data[:,1]>upper_quartile_minutes),1] = upper_quartile_minutes # ограничение значений верхним квартилем
print(data)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [73]:
zero_minutes_count = np.sum(data[:,1]==0)
data[data[:,1]==0, 1] = 1
print('рецептов с нулевой продолжительностью:', zero_minutes_count,'скорректированный датасет', data, sep = '\n')

рецептов с нулевой продолжительностью:
0
скорректированный датасет
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [75]:
unique_recipes_count = np.unique(data[:,1:], axis = 0).shape[0] #подсчет количества уникальных рецептов без учета 1 столбца (id)
print('уникальных рецептов:', unique_recipes_count, '\n')

уникальных рецептов: 1135 



6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [78]:
ingredients, ingredients_count = (np.unique(data[:,2], return_counts = True))
print('значение кол-ва ингредиентов, количество таких рецептов', np.hstack([np.reshape(ingredients, (ingredients.shape[0], 1)),
           np.reshape(ingredients_count,(ingredients_count.shape[0], 1))]), sep = '\n')

значение кол-ва ингредиентов, количество таких рецептов
[[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [79]:
max5_ingredients_data = data[data[:,2]<=5] # запись в новый массив данных только о рецептах, в которых <= 5 ингредиентов 
print('рецепты, состоящие не более чем из 5 ингредиентов', max5_ingredients_data, sep = '\n')

рецепты, состоящие не более чем из 5 ингредиентов
[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [80]:
mean_inredients = data[:,2]/data[:,1]
print('максимальное среднее значение ингредиентов в минуту', mean_inredients.max(0), sep = '\n')

максимальное среднее значение ингредиентов в минуту
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [81]:
data_sorted = data[np.argsort(data[:,1])[::-1]] # создание массива с отсортированным по продолжительности датасетом
print('среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью', data_sorted[:100,2].mean(0), sep = '\n') # поиск среднего количества ингредиентов среди первых ста рецептов в отсортированном датасете

среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью
9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [82]:
random_10recipes_data = data[np.random.choice(data.shape[0], 10, replace = False)]
print('10 случайных различных рецепта', random_10recipes_data, sep = '\n')

10 случайных различных рецепта
[[309231     50     15]
 [288018     35     10]
 [487827     10      9]
 [315326     20     12]
 [331842     65     12]
 [157562     48      6]
 [ 93690     10      6]
 [172474     25      4]
 [104992     65     14]
 [424931     20      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [84]:
print('процент рецептов, кол-во ингредиентов в которых меньше среднего', np.sum(data[:,2]<data[:,2].mean(0))*100/data.shape[0], sep = '\n')

процент рецептов, кол-во ингредиентов в которых меньше среднего
58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [85]:
easy_recipes_flag = (data[:,1]<=20).reshape(data.shape[0],1)*(data[:,2]<=5).reshape(data.shape[0],1)
easy_recipes_data = np.hstack((data,easy_recipes_flag))
print(easy_recipes_data)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [86]:
print('процент "простых" рецептов в датасете', np.sum(easy_recipes_flag)*100/data.shape[0], sep = '\n')

процент "простых" рецептов в датасете
9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [87]:
min_time_group_count = np.min(np.array([data[(data[:,1]<10)].shape[0], data[((data[:,1]>=10)*(data[:,1]<20))].shape[0], data[(data[:,1]>=20)].shape[0]]))
time_group_data = np.array([data[data[:,1]<10][:min_time_group_count,:], data[(data[:,1]>=10)*(data[:,1]<20)][:min_time_group_count,:], data[(data[:,1]>=20)][:min_time_group_count,:]])
print('форма 3-мерного массива', time_group_data.shape, sep = '\n')

форма 3-мерного массива
(3, 7588, 3)
